# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "yongchun"
BBFILE_PATTERN_yongchun = "^${LAYERDIR}/"
BBFILE_PRIORITY_yongchun = "10"

LAYERDEPENDS_yongchun = "core fsl-bsp-release"
LAYERSERIES_COMPAT_yongchun = "wrynose"
